import { Item } from './types'
const ago=(days:number)=>new Date(Date.now()-days*86400000).toISOString()
export const demoItems:Item[]=[
{id:'demo-internship',title:'Internship Application',category:'Career',description:'Complete the final application for the summer internship.',createdAt:ago(34),lastActivityAt:ago(28),deadline:ago(-7),importance:'high',status:'active',nextAction:'Upload resume',estimatedMinutes:4,dependencies:['demo-portfolio','demo-github'],consequence:'Application may remain incomplete before the deadline.',history:[{at:ago(34),type:'created'}],demo:true},
{id:'demo-project',title:'College Website Project',category:'College',description:'Finish the authentication flow and document the project.',createdAt:ago(24),lastActivityAt:ago(12),deadline:ago(-15),importance:'high',status:'active',nextAction:'Create the login page',estimatedMinutes:15,dependencies:['demo-github'],consequence:'The project submission could be delayed.',history:[{at:ago(24),type:'created'}],demo:true},
{id:'demo-course',title:'Python Course',category:'Learning',description:'A practical course you started and want to finish.',createdAt:ago(45),lastActivityAt:ago(10),importance:'medium',status:'active',nextAction:'Complete module 3 quiz',estimatedMinutes:25,dependencies:[],consequence:'Momentum may fade and the course may be abandoned.',history:[{at:ago(45),type:'created'}],demo:true},
{id:'demo-event',title:'Hackathon Registration',category:'Events',description:'Confirm attendance and prepare your profile.',createdAt:ago(14),lastActivityAt:ago(8),deadline:ago(-3),importance:'medium',status:'active',nextAction:'Confirm attendance',estimatedMinutes:2,dependencies:[],consequence:'Your registration may expire.',history:[{at:ago(14),type:'created'}],demo:true},
{id:'demo-portfolio',title:'Portfolio Update',category:'Career',description:'Add your latest project case study.',createdAt:ago(50),lastActivityAt:ago(21),importance:'medium',status:'active',nextAction:'Write the project summary',estimatedMinutes:12,dependencies:[],consequence:'Your application materials may look out of date.',history:[{at:ago(50),type:'created'}],demo:true},
{id:'demo-warranty',title:'Laptop Warranty Registration',category:'Personal',description:'Register the new laptop before the window closes.',createdAt:ago(5),lastActivityAt:ago(5),deadline:ago(-22),importance:'low',status:'active',nextAction:'Find the serial number',estimatedMinutes:5,dependencies:[],consequence:'Warranty coverage could be harder to claim.',history:[{at:ago(5),type:'created'}],demo:true}
]
